# Generated by Django 5.2 on 2025-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parceiro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parceiro',
            name='cnpj',
            field=models.CharField(default='00000000000000', max_length=14),
        ),
    ]
