# Generated by Django 5.2 on 2025-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='senha',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Senha de acesso'),
        ),
    ]
