# Generated by Django 5.2 on 2025-05-03 21:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('reservas', '0002_alter_reserva_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cnpj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='parceiros.parceiro'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='2f18d14898', max_length=10, primary_key=True, serialize=False),
        ),
    ]
