# Generated by Django 5.2 on 2025-05-17 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('reservas', '0003_alter_reserva_cnpj_alter_reserva_data_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cnpj',
            field=models.ForeignKey(default='00000000000000', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='parceiros.parceiro'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='235d7f43e9', max_length=10, primary_key=True, serialize=False),
        ),
    ]
