# Generated by Django 5.2 on 2025-05-17 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_reserva_cnpj_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='8c5970d546', max_length=10, primary_key=True, serialize=False),
        ),
    ]
