# Generated by Django 5.2 on 2025-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_reserva_created_at_reserva_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='50b1a78690', max_length=10, primary_key=True, serialize=False),
        ),
    ]
