# Generated by Django 5.2 on 2025-05-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_alter_reserva_numero_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='numero_reserva',
            field=models.CharField(default='ea975a96c7', max_length=10, primary_key=True, serialize=False),
        ),
    ]
